# Generated by Django 5.2.8 on 2025-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('in_assembly', 'В сборке'), ('ready', 'Готов к выдаче'), ('delivered', 'Выдан')], default='created', max_length=20, verbose_name='Статус'),
        ),
    ]
